name: groviq
description: Groviq - Blinkit style grocery & food delivery Flutter app
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: any
  http: any
  cached_network_image: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
